import json
from backend.config import SUGGESTED_QUESTIONS_PATH
from backend.utils.logger import get_logger

logger = get_logger(__name__)

_cache = None


def get_suggested_questions(workspace: str) -> list[str]:
    """
    Returns the curated starter questions for a given workspace
    ("policy" or "pdf_chat"). Loaded from a static JSON file, not
    generated by an LLM — keeps this instant and free, and lets you
    hand-pick which questions get showcased in a demo.
    """
    global _cache

    if _cache is None:
        try:
            with open(SUGGESTED_QUESTIONS_PATH, "r", encoding="utf-8") as f:
                _cache = json.load(f)
        except Exception as e:
            logger.warning(f"Failed to load suggested questions: {e}")
            _cache = {}

    return _cache.get(workspace, [])